INVENTORY_URL = "inventory.html"
SHOPPING_CART_LOCATOR = "[data-test='shopping-cart-link']"
ERROR_MESSAGE_LOCATOR = "[data-test='error']"
ERROR_MESSAGE = "Epic sadface: Username and password do not match any user in this service"
USERNAME_REQUIRED_MESSAGE = "Epic sadface: Username is required"
PASSWORD_REQUIRED_MESSAGE = "Epic sadface: Password is required"
PASSWORD_LOCATOR = "#password"
USERNAME_LOCATOR = "#user-name"
SUBMIT_BUTTON_LOCATOR = "#login-button"
SQL_INJECTION_INPUT = "' OR '1'='1"
SHOPPING_CART_BADGE_LOCATOR = "[data-test='shopping-cart-badge']"
BACK_TO_PRODUCTS_LOCATOR = "#back-to-products"
ITEM_DESCRIPTION_LOCATOR = "[data-test='inventory-item-desc']"
ITEM_LOCATOR = "[data-test='inventory-item-name']"
SORT_LOCATOR = "[data-test='product-sort-container']"
PRICE_LOCATOR = "[data-test='inventory-item-price']"

